Repository action-is-hope/shelley, pull requests merged in 2023-07, with the labels that each got.

#113 feat(component): Disclosure
  .vscode/settings.json
  cypress/component/Disclosure.cy.tsx
  cypress/component/DisclosureGroup.cy.tsx
  src/Button/Button.tsx
  src/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/Button/button.st.css
  src/DisclosureGroup/Disclosure.tsx
  src/DisclosureGroup/DisclosureGroup.tsx
  src/DisclosureGroup/disclosure.st.css
  src/DisclosureGroup/disclosureGroup.st.css
  src/DisclosureGroup/index.ts
  src/DisclosureGroup/useDisclosure.tsx
  src/Icon/Icon.tsx
  src/Icon/icon.st.css
  src/Modal/modal.st.css
  src/indexLib.ts
  src/stories/UI/DialogTrigger.stories.mdx
  src/stories/UI/DisclosureGroup.examples.tsx
  src/stories/UI/DisclosureGroup.stories.mdx
  src/styles/default/disclosure.st.css
  src/styles/default/disclosureGroup.st.css
  src/styles/default/index.ts
  src/styles/default/modal.st.css
  src/styles/shelley/disclosureGroup.st.css
  src/styles/shelley/index.ts
Labels: documentation, story, component

#136 SHELLEY-135: Add missing bits on ProgressBar #135
  src/ProgressBar/ProgressBar.tsx
  src/stories/UI/ProgressBar.stories.mdx
Labels: Shelley

#123 feat(component): Notification
  cypress/component/Notification.cy.tsx
  src/Notification/Notification.tsx
  src/Notification/index.ts
  src/Notification/notification.st.css
  src/indexLib.ts
  src/stories/UI/Notification.examples.tsx
  src/stories/UI/Notification.stories.mdx
  src/styles/default/index.ts
  src/styles/default/notification.st.css
  src/styles/shelley/notification.st.css
Labels: component, P1
